#!/bin/sh
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$project_dir"
mkdir -p bin
GOEXPERIMENT=nodwarf5 go build -o bin/zill ./cmd/zill
exec perf record -g -o bin/perf.data -- bin/zill "$@"
